spring:
  application:
    name: utaha
#    type: dubbo
  profiles:
    active: local     # 本地开发环境
#    active: dev       # 开发环境
#    active: test      # 测试环境
#    active: pre       # 预发环境
#    active: online    # 生产环境
  devtools:
    livereload:
      enabled: true
      # 静态文件请求匹配方式
  mvc:
    static-path-pattern: /**
      # 修改默认的静态寻址资源目录
    throw-exception-if-no-handler-found: true #全局异常控制
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/static

#logging:
#  config: classpath:katou-logback.xml

# health monitor
info:
  app:
    name: "Utaha"
    description: "Utaha the RPC consumer"
    version: "1.0.0-SNAPSHOT"
    springBootVersion: "1.5.8.RELEASE"

management:
  security:
    enabled: false
